# Generated by Django 2.0.4 on 2018-04-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_name', models.TextField()),
                ('teacher_name', models.TextField()),
            ],
        ),
    ]
